#!/bin/bash

function usage {
    echo
    echo "Usage:"
    echo "$0 <hostname>"
    echo
    exit 0
}
if [ $# -ne 1 ]; then
    usage
fi

host=$1
retry_counter=0
max_sleep_time=60

function sleepy() {
        # sleep for 1 - 6 seconds
        sleep_time=$[( $RANDOM % 5 ) +1]
        if [[ $sleep_time < $max_sleep_time ]]; then
            sleep_time=$(( $sleep_time + $(( $retry_counter * 2 )) ))
            echo "[ $date ] Host $host is down, sleeping for $sleep_time seconds"
            sleep $sleep_time
        fi
}

# first check if this is a hostname and if it is check if it can be resolved
if echo "$host" | grep -E "^[0-9\.]+$" > /dev/null; then
    echo "Connecting to IP address $host"
else
    if ! host "$host" > /dev/null; then
        echo "Failed to do hostname resolution for $host"
        exit 1
    fi
fi

while true; do
        if ssh -o ConnectTimeout=2 "$host" id 2>1 | grep -q "uid="; then
            ssh "$host"
            exit $?
        else
            date=$(date)
            sleepy
            retry_counter=$(($retry_counter +1 ))
        fi
done

